/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'denis' at '03.08.16 2:01' with Gradle 2.14
 *
 * @author denis, @date 03.08.16 2:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
